# Generated by Django 2.1.7 on 2019-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190413_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
