# Generated by Django 2.1.7 on 2019-04-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190327_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='education',
        ),
    ]
